# Generated by Django A.I. on 2025-11-06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="exercise_goal",
            field=models.CharField(blank=True, choices=[("MUSCLE_GAIN", "근육량 증가"), ("DIET", "다이어트")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="inbody_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bmi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="body_fat_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skeletal_muscle_mass_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="body_fat_mass_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="segment_right_arm_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="segment_left_arm_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="segment_trunk_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="segment_right_leg_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="segment_left_leg_kg",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
